### ISSUE TITLE
[CLIFF] What are the constant values in CLIFF demo.py when processing bbox_info?

### ISSUE THREAD

**Issue by chenmingTHU** [huawei-noah/noah-research#105]
![image](https://user-images.githubusercontent.com/22796506/184085884-0ce8185b-c87d-403d-9592-490f98229613.png)
 What are the constant values 2.8, 0.24, 0.06 means? They are different from the original equations in the paper.
![image](https://user-images.githubusercontent.com/22796506/184086216-6b547f88-090d-40f1-a2a4-22667f99dad9.png)

**Comment by zhihaolee** [comment]
Please refer to #94 .
