### ISSUE TITLE
[CLIFF] hrnet48 checkpoint; image shape of in-the-wild datasets; is 3dpw traningset included for 69.0?

### ISSUE THREAD

**Issue by winshot-thu** [huawei-noah/noah-research#110]
Hi,
Thanks for your great works!
Could you please release hr48 pretrained model of '../backbones/hrnet/models/cls_hrnet_w48_sgd_lr5e-2_wd1e-4_bs32_x100.yaml'?

**Comment by zhihaolee** [comment]
You can find it at the [HRNet-Image-Classification](https://github.com/HRNet/HRNet-Image-Classification) official repo.

**Comment by winshot-thu** [comment]
> You can find it at the [HRNet-Image-Classification](https://github.com/HRNet/HRNet-Image-Classification) official repo.

@zhihaolee Thanks a lot for your kind reply! I mistook deep-high-resolution-net.pytorch as pre-trained backbone..

Another questions. What is the shape you cropped in  coco2014part_cliffGT.npz and mpii_cliffGT.npz datasets? 256X256 or 256X192?

**Comment by winshot-thu** [comment]
Besides, I'd like to double check, Table.1 CLIFF (HR-W48) MPJPE 69.0 is trained on some datasets including **3DPW training set**, right?

**Comment by zhihaolee** [comment]
1. The aspect ratio in the cliff_GT is 4:3 (256x192). You can regenerate the `scale` data for different aspect ratios using the 2D keypoints.
2. Yes, 3DPW training set is included for MPJPE 69.0 in the 3dpw evaluation.

**Comment by winshot-thu** [comment]
Thanks for your reply!
