### ISSUE TITLE
CLIFF 如何使用weak cam参数渲染到224x224的图像上

### ISSUE THREAD

**Issue by LastXuanDog** [huawei-noah/noah-research#114]
@zhihaolee CLIFF给的checkpoint输入是256x192的图片，得到weak_cam为[s, tx, ty]，然后转换到原图大小的[tx', ty', tz']。我是用[PARE的这个函数](https://github.com/mkocabas/PARE/blob/6e0caca86c6ab49ff80014b661350958e5b72fd8/pare/utils/geometry.py#L286)转换的，focal_length是用的CLIFF的，res是224，但好像渲染出来的大小不是很对，请问如何用CLIFF估计出来的256x192弱透视相机参数转换到224x224的透视相机的参数呢？

**Comment by zhihaolee** [comment]
应该可以直接转换的。具体是怎样不对呢，你可以发图片上来看看吗？
而且你应该要用[这个函数](https://github.com/mkocabas/PARE/blob/6e0caca86c6ab49ff80014b661350958e5b72fd8/pare/utils/geometry.py#L309)吧，你好像正好用反了。

**Comment by LastXuanDog** [comment]
@zhihaolee 谢谢您的解答，我发现我忘记把smpl模型的transl那个位移`transl=pred_cam_full`注释掉了，所以会有点偏小，现在正常了。

我还发现有个问题，就您给的mpii数据集是不是少了[这个操作](https://github.com/nkolot/SPIN/blob/5c796852ca7ca7373e104e8489aa5864323fbf84/datasets/preprocess/mpii.py#L26-L28)，您提供的伪标签有2w多个，而SPIN只有1w多个。

还有个问题就是您制作的伪标签里面能提供一下对应的openpose么，[SPIN的估计GT_cam_t](https://github.com/nkolot/SPIN/blob/5c796852ca7ca7373e104e8489aa5864323fbf84/utils/geometry.py#L135-L142)会用到，我自己一个个去匹配有点困难。

**Comment by zhihaolee** [comment]
- 我们所提供的MPII伪标签有16383个。当初处理MPII数据时，的确有个小问题，导致某张图片里如果有一个样本是全身可见的，那么这张图片里的所有样本都会加入训练集里。
- CLIFF里没有使用run_simplify，也没有使用SPIN提供的final_fits。

**Comment by LastXuanDog** [comment]
@zhihaolee MPI-INF-3DHP有些样本是没有3d注释的，这些样本使用SPIN的fits做监督会不会能提升分数呢

**Comment by zhihaolee** [comment]
我们使用了`mpi-inf-3dhp_mview_fits.npz`，把所有`has_smpl`标志设为True。
你使用SPIN得到的fits应该也可以，但我不知道是否能提升分数。
