### ISSUE TITLE
cliff result not good

### ISSUE THREAD

**Issue by AmberCheng** [huawei-noah/noah-research#116]
Thanks for your wonderful job！I recently test a video both on CLIFF and PARE. However, the CLIFF get worse result than PARE.  I wonder does it because the half body scene is not suitable for CLIFF ?

https://user-images.githubusercontent.com/18375990/191909405-9259a2e1-9efd-4b04-95d7-759515a1de06.mp4

https://user-images.githubusercontent.com/18375990/191912283-de0a91ec-f65a-41c1-b815-2d1ebbde51a8.mp4

**Comment by AmberCheng** [comment]
https://user-images.githubusercontent.com/18375990/191910135-18ad5dee-ffee-448c-9193-5ed1e4817a37.mp4

**Comment by zhihaolee** [comment]
Have you tried the HRNet-backbone model `hr48-PA43.0_MJE69.0_MVE81.2_3dpw.pt`? It would be better.

**Comment by AmberCheng** [comment]
> Have you tried the HRNet-backbone model `hr48-PA43.0_MJE69.0_MVE81.2_3dpw.pt`? It would be better.

Thanks for your reply! I have tried the  HRNet-backbone model , and the result is much more better!

**Comment by zhihaolee** [comment]
@AmberCheng 
Could you please share the video result? So that we can know how it goes, thank you!

**Comment by AmberCheng** [comment]
> @AmberCheng Could you please share the video result? So that we can know how it goes, thank you!

Sorry for late. Here is the HRNet backbone result. 



https://user-images.githubusercontent.com/18375990/194736269-5129f4e0-cd95-4a66-a437-66f2cd333311.mp4
