### ISSUE TITLE
[CLIFF] How to re-project smpl_joints into 2D keypoints on image plane?

### ISSUE THREAD

**Issue by haofanwang** [huawei-noah/noah-research#119]
As title, is it possible to calculate MPJPE-2D for any given images in the wild?

**Comment by zhihaolee** [comment]
After getting the 3D joints, please refer to [this](https://github.com/nkolot/SPIN/blob/5c796852ca7ca7373e104e8489aa5864323fbf84/utils/geometry.py#L63) for perspective projection.

**Comment by haofanwang** [comment]
Hi @zhihaolee, I have used the perspective projection, but the projected keypoints are not aligned to the right human position. Is there anything I have missed? The code is attached below for reference.

```
with torch.no_grad():
    pred_rotmat, pred_betas, pred_cam_crop = cliff_model(norm_img, bbox_info)

# convert the camera parameters from the crop camera to the full camera
full_img_shape = torch.stack((img_h, img_w), dim=-1)
pred_cam_full = cam_crop2full(pred_cam_crop, center, scale, full_img_shape, focal_length)

pred_output = smpl_model(betas=pred_betas,
                         body_pose=pred_rotmat[:, 1:],
                         global_orient=pred_rotmat[:, [0]],
                         pose2rot=False,
                         transl=pred_cam_full)

points_3d = pred_output.joints()
batch_size = points_3d.shape[0]
keypoints_2d = perspective_projection(points_3d,
                                      rotation=torch.eye(3, device=points_3d.device).unsqueeze(0).expand(batch_size, -1, -1),
                                      translation=pred_cam_full,
                                      focal_length=focal_length,
                                      camera_center=torch.zeros(batch_size, 2, device=points_3d.device))

```

It would be grateful if you could help, thanks.

**Comment by zhihaolee** [comment]
It should be right after you make the keypoints_2d centered at the image center. 
Could you show me the visualized result?

**Comment by haofanwang** [comment]
Thanks for your suggestion and I further add the following lines. The result is as below. @zhihaolee 

```
keypoints_2d[:,:,0] += img_w[:,None] / 2.0
keypoints_2d[:,:,1] += img_h[:,None] / 2.0
```

https://user-images.githubusercontent.com/18741068/192460567-c2b1ec73-7112-43c1-9cc1-80812322d97d.mp4

**Comment by ShamLich** [comment]
> Thanks for your suggestion, it works after I set camera_center to the image center.



> Thanks for your suggestion, it works after I set camera_center to the image center.

hi,@haofanwang ,can you share your re-project code?

**Comment by ShamLich** [comment]
> Thanks for your suggestion, it works after I set camera_center to the image center.

hi,@haofanwang ,can you share your re-project code?

**Comment by pppkkk611** [comment]
> It should be right after you make the keypoints_2d centered at the image center. Could you show me the visualized result?

`points_3d = pred_output.joints
        batch_size = points_3d.shape[0]
        # Assuming img_w and img_h are the width and height of the image
        img_w_value = img_w[0].item()
        img_h_value = img_h[0].item()
        camera_center = torch.tensor([[img_w_value / 2, img_h_value / 2]], dtype=torch.float32, device=points_3d.device)
        camera_center = camera_center.expand(batch_size, 2)
        keypoints_2d = perspective_projection(points_3d,
                                      rotation=torch.eye(3, device=points_3d.device).unsqueeze(0).expand(batch_size, -1, -1),
                                      translation=pred_cam_full,
                                      focal_length=focal_length,
                                      camera_center=camera_center)
`
![1700640433205](https://github.com/huawei-noah/noah-research/assets/76949781/1dd428a1-9875-445b-aec2-f8aa53ae1b00)
I don‘t know how to solve it.
