### ISSUE TITLE
[CLIFF] model.train和model.eval预测出来的结果差距很大

### ISSUE THREAD

**Issue by LastXuanDog** [huawei-noah/noah-research#122]
@zhihaolee 使用的是提供的checkpoint，输入的batch_size都是1。
![2022-09-28_23-51-24](https://user-images.githubusercontent.com/113993987/192827579-dad96426-98f3-4cb1-97d2-51e331aa760f.png)
这是`model.eval()`预测出来的。

![2022-09-28_23-53-39](https://user-images.githubusercontent.com/113993987/192827700-d33df74a-fe96-4313-8cf0-8a1165ab71c4.png)
这是`model.train()`预测出来的。

其他什么都没有动，为什么`model.train()`预测出来的会偏差这么大？

**Comment by zhihaolee** [comment]
model.train()模式下，BN的参数会更新，dropout是随机的。
model.eval()模式下，BN才会使用训练好的参数，dropout才不是随机的。
