### ISSUE TITLE
[CLIFF] 关于SMPL的监督

### ISSUE THREAD

**Issue by Me-Ditto** [huawei-noah/noah-research#126]
论文里在监督时使用的是相对根节点的SMPL进行监督，论文也写明可以回归得到相机坐标系下的根关节的平移，在SMPL模型上叠加根关节的平移可以得到相机坐标系下的SMPL，请问为什么不能直接使用相机坐标系下的SMPL模型进行监督呢？

**Comment by zhihaolee** [comment]
也可以直接使用相机坐标系下的SMPL模型进行监督，但目前大家的做法大都是使用相对根节点的SMPL进行监督，可能是因为这样可以解耦根节点平移估计和3D姿态估计这两个问题，方便训练网络。
