### ISSUE TITLE
[CLIFF] Novel view visualization

### ISSUE THREAD

**Issue by MooreManor** [huawei-noah/noah-research#131]
Can you offer the code to render the novel view of mesh in paper?
![image](https://user-images.githubusercontent.com/49632327/196926977-bc21b1dc-b479-4b84-806a-46687d521b58.png)

**Comment by zhihaolee** [comment]
I did this manually. 1) save these meshes as obj files, 2) open the obj files in MeshLab, 3) save snapshots.

**Comment by faaronts** [comment]
How can the meshes be saved as obj files?
