### ISSUE TITLE
[CLIFF] Will CLIFF offer MPI-INF-3DHP fits in the future

### ISSUE THREAD

**Issue by MooreManor** [huawei-noah/noah-research#133]
Some of the SPIN used multiview fits for MPI-INF-3DHP are in weird shapes. Will CLIFF consider offering better quality MPI-INF-3DHP fits in the future?

**Comment by zhihaolee** [comment]
Maybe later, maybe not, not sure yet. 
We used the same multi-view fits for MPI-INF-3DHP, and just filtered out the weird frames.

**Comment by MooreManor** [comment]
@zhihaolee How do you filter out the weird frames? Do you use the rule according to the 3d keypoint error?

**Comment by zhihaolee** [comment]
The filtering is like the one in SPIN, using the reprojection difference between the GT 3D joints and GT 2D keypoints.
