### ISSUE TITLE
[CLIFF] Inference on top-view images

### ISSUE THREAD

**Issue by neelesh314** [huawei-noah/noah-research#134]
Thanks for your great work. Do you have any suggestions on how to improve results for images acquired from a camera positioned at the top? What ends up happening is that for such top-view images, the lower-body results are completely wrong.

**Comment by zhihaolee** [comment]
Could you show some sample images and their results?

**Comment by zhihaolee** [comment]
The result seems okay to me. Why did you say the lower-body results are completely wrong?

**Comment by neelesh314** [comment]
Thanks for continuing to engage :) The generated pose is in a sitting position while the actual subject is not.

**Comment by zhihaolee** [comment]
Could you show the original image, then we can know the real pose?

**Comment by neelesh314** [comment]
Here is the original image 
![115_frame](https://user-images.githubusercontent.com/15177642/200831317-1de70bbf-1616-445e-9ea4-e5ac5a575838.jpg)

**Comment by zhihaolee** [comment]
Now I can tell this person is standing straight actually. 
To improve the results for images acquired from a camera positioned at the top, we can collect such images, annote the 2D keypoints (manually or via the keypoint detection), use the CLIFF annotator to get the pseudo-GT and put these data into training, finally we may get better results.
