### ISSUE TITLE
[CLIFF]关于重投影误差的loss

### ISSUE THREAD

**Issue by Me-Ditto** [huawei-noah/noah-research#135]
你好，论文中使用重投影误差是为了能够利用更多的2D数据，但是我们在具有3D groundtruth 的数据集上进行训练时，发现加入重投影误差的loss会使得结果的精度降低，请问在所有数据都有3D groundtruth的情况下，理论上会出现这种情况吗？

**Comment by zhihaolee** [comment]
应该不会，有可能是重投影误差没弄好，可以训练时做可视化检查确认一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月30日(周日) 下午2:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [huawei-noah/noah-research] [CLIFF]关于重投影误差的loss (Issue #135)




 
你好，论文中使用重投影误差是为了能够利用更多的2D数据，但是我们在具有3D groundtruth 的数据集上进行训练时，发现加入重投影误差的loss会使得结果的精度降低，请问在所有数据都有3D groundtruth的情况下，理论上会出现这种情况吗？

**Comment by Me-Ditto** [comment]
在原始图片上计算重投影误差，计算的结果作为loss的时候需要做normalization吗？

**Comment by zhihaolee** [comment]
重投影误差的计算基本跟SPIN的一样，仅仅是重投影那一步不一样而已。
也就是说，跟SPIN一样要做normalization。

**Comment by Me-Ditto** [comment]
感谢您的回复！
