### ISSUE TITLE
Suggestion: save user from finding min

### ISSUE THREAD

**Issue by microprediction** [huawei-noah/noah-research#14]
Hi, just a little suggestion and maybe I missed it in the code, but why not insert something like: 

    best_val = opt.y.min()
    best_ndx = np.argmin([y[0] for y in opt.y])
    best_x = list(opt.X.values[best_ndx])

so the user doesn't have to?

**Comment by huawei-noah-admin** [comment]
Thank you for your attention to this repo.
Because there are several subprojects in this repo, could you help to tell me which subproject this issue is for?
Thank you very much!

**Comment by Alaya-in-Matrix** [comment]
@microprediction Yeah that would be great, I'll include it in my next commit.
