### ISSUE TITLE
[CLIFF] A data problem on Agora

### ISSUE THREAD

**Issue by cyk990422** [huawei-noah/noah-research#156]
Hi,Zhihao!
This is an excellent job. I had a small problem when I reproduced it on Agora. The global rotation parameter in SMPL parameters given by Agora is in the world coordinate system. How did you convert it to the camera coordinate system?

**Comment by zhihaolee** [comment]
Get the camera yaw and pitch angles, then calculate the camera rotation matrix. Besides the camera rotation, you need to multiply  smpl yaw rotation matrix.

**Comment by cyk990422** [comment]
Thank you very much for your patient reply!

**Comment by ShamLich** [comment]
> Get the camera yaw and pitch angles, then calculate the camera rotation matrix. Besides the camera rotation, you need to multiply smpl yaw rotation matrix. Please refer to [pixelite1201/agora_evaluation#14](https://github.com/pixelite1201/agora_evaluation/issues/14).

you mean (camera_rotationMatrix@camera_rotationMatrix2@rotMat@root_pose)？
