### ISSUE TITLE
TNT code

### ISSUE THREAD

**Issue by doursand** [huawei-noah/noah-research#16]
hey, 

Thanks for the awesome work ! I'm super interested to experiment with your TNT approach ... any idea when the code might be released ?

**Comment by iamhankai** [comment]
A thirdparty implementation can be found at https://github.com/lucidrains/transformer-in-transformer.

We are preparing the code and will opensource as soon.

**Comment by doursand** [comment]
great tx, i will take a look. Will you also provide pretrained weights to do transfer learning ?

**Comment by doursand** [comment]
last question, in the paper you said that you trained on V100 GPUs. Out of curiosity, how many gpus did you use ?

**Comment by iamhankai** [comment]
8 V100 GPUs for 1024/512 batch size.
