### ISSUE TITLE
[TNT] Positional encoding & further experiment plan

### ISSUE THREAD

**Issue by LostXine** [huawei-noah/noah-research#17]
Hello,

Thank you for this amazing work.

Regarding the "standard" 1D position encoding, are you saying that the sequence of patches is in raster order, and the position encoding is only applied to the first layer of the TNT?

And, just curious, do you have a plan for further experiments or visualizations (if you want to talk about it)? 

Thank you for your time and patience.

Best,

**Comment by iamhankai** [comment]
1. Similar to ViT, the position encoding is only applied to the first layer.
2. We're conducting further experiments and will update the results upon the progress.

**Comment by LostXine** [comment]
Thank you for your reply, and have a good one :)
