### ISSUE TITLE
[TokenFusion]AttributeError: 'Namespace' object has no attribute 'ckpt'

### ISSUE THREAD

**Issue by CE-AI** [huawei-noah/noah-research#172]
我是一个初学者，请问这个错误的解决方案是什么。是不是因为训练的时候没有指定文件的放置路径，所以没有生成ckpt文件。我应该如何修改这个问题呢？期待您的解答，谢谢！

**Comment by CE-AI** [comment]
在windows10下，python和pytorch版本和其他环境均与要求环境一致。执行评估语句会出现该错误提示。
`python main.py --gpu 0 --resume path_to_pth --evaluate`
由于个人原因已经将原文件卸载，这几天将会使用ubuntu22.04重新尝试模型的训练与评估。谢谢您的解答

**Comment by xinghaochen** [comment]
需要把path_to_pth替换成实际的ckpt路径

**Comment by CE-AI** [comment]
我稍后会尝试，当时好像并没有生成ckpt为后缀的文件。但是有生成文件名带有checkpoint的（后缀我忘记了）。谢谢您。

**Comment by CE-AI** [comment]
我不太确定具体的引用路径是什么。

**Comment by CE-AI** [comment]
尝试引用到这几个路径下都表示no checkpoint found
```
semantic_segmentation/ckpt/exp_name/model-best.pth.tar
semantic_segmentation/ckpt/exp_name/checkpoint.pth.tar
semantic_segmentation/ckpt
semantic_segmentation/ckpt/exp_name
```

**Comment by xinghaochen** [comment]
大概率还是路径问题，如果你是直接运行的`python main.py --gpu 0 --resume path_to_pth --evaluate`，那意味着当前路径已经在semantic_segmentation里面，所以你的ckpt路径就不该有这一层
