### ISSUE TITLE
[CLIFF]Will you release models trained on 224*224 resolution?

### ISSUE THREAD

**Issue by Timkeeper2018** [huawei-noah/noah-research#173]
Sorry to bother you, as the title describes, are you planning to release the pre-trained model at 224*224 resolution?
Because I want to reproduce your results but I can't apply for the qualification of the h36m data set. The previous work only has the preprocessed h36m data set, and they are processed at 224*224 resolution.

Here is my email if possible
hackerclaymore@gmail.com

**Comment by zhihaolee** [comment]
Sorry that I deleted the checkpoints trained at 224x224, so I can't release them.
