### ISSUE TITLE
Missing code for TD4CL

### ISSUE THREAD

**Issue by erip** [huawei-noah/noah-research#177]
The link to [this paper](https://aclanthology.org/2022.emnlp-main.167.pdf) on training dynamics-based curriculum learning is dead. The paper doesn't seem to be in the repo. Would it be possible to add it?

**Comment by ospanbatyr** [comment]
Same issue

**Comment by fenchri** [comment]
Hello everyone,

Apologies for the delay, we have finally released the code! 
Feel free to have a look and report any questions/issues. 

Thank you :)
