### ISSUE TITLE
HEBO suggests the same parameters multiple times

### ISSUE THREAD

**Issue by qo4on** [huawei-noah/noah-research#28]
Why does `opt.suggest` suggest the same parameters multiple times?
```
space_cfg = [
    {'name': 'n_estimators',     'type': 'int', 'lb': 20, 'ub': 21},
    {'name': 'max_depth',        'type': 'int', 'lb': 2, 'ub': 3},
]
```
```
{'n_estimators': 20, 'max_depth': 2}
{'n_estimators': 20, 'max_depth': 2}
{'n_estimators': 21, 'max_depth': 2}
{'n_estimators': 20, 'max_depth': 3}
The value argument must be within the support
```
HEBO suggests `{'n_estimators': 20, 'max_depth': 2}` twice and throws an error while there is one hp configuration remains untested: `{'n_estimators': 21, 'max_depth': 3}`.

**Comment by Alaya-in-Matrix** [comment]
It seems that the search space is so small (2 * 2 = 4), so that HEBO has enumerated all possible combination

**Comment by qo4on** [comment]
I believe this is incorrect behavior. @smcdonagh, @iamhankai please take a look at this.

**Comment by smcdonagh** [comment]
Hi @qo4on  -- I am not part of the HEBO project, apologies.

**Comment by alexanderimanicowenrivers** [comment]
@qo4on This is correct behaviour and I will close this issue. If you look at your design space you only have two variables for n_estimators (20, 21) and two for max_depth (2,3) so there's going to be expected overlap, typical search spaces are much larger.
