### ISSUE TITLE
Location code

### ISSUE THREAD

**Issue by Dpw506** [huawei-noah/noah-research#30]
With the position encoding of patch size, how should its position and position be decoded?The position of the pixels is the same.

**Comment by huawei-noah-admin** [comment]
Thank you for your attention to this repo.
Because there are several subprojects in this repo, can you help to tell me which subproject this issue is for?
Thank you very much!

**Comment by Dpw506** [comment]
Yes, I just want to see the final output image of TNT, just want to see the final output image of TNT, if it is a sub-task, it should be a detection task.Thank you so much!

**Comment by iamhankai** [comment]
I didn't get your point. Could you clarify your question?

**Comment by Dpw506** [comment]
My mean is that I want to see how TNT can be output as a three-dimensional image instead of a two-dimensional array. This is where I am puzzled, because I tried some methods but the output is wrong.

**Comment by iamhankai** [comment]
The `HxWxC` dimensions are reshaped into `(HW)xC`.

**Comment by Dpw506** [comment]
Yes, I know it are reshaped into (HW)*C and I had reshapede into H*W*C again, but the output image is a completely noisy. Have you tried to output image？What should I do to get the final image?

**Comment by Dpw506** [comment]
Yes, I know it are reshaped into (HW)_C and I had reshapede into H*W*C again, but the output image is a completely noisy. Have you tried to output image？What should I do to get the final image?

**Comment by iamhankai** [comment]
The output is the feature map, not image. It looks like noise, not natural image.
