### ISSUE TITLE
[BO-HEBO] HEBO breaks with pymoo>=0.5.0

### ISSUE THREAD

**Issue by Yard1** [huawei-noah/noah-research#41]
With the newest release of pymoo (https://github.com/anyoptimization/pymoo/releases/tag/0.5.0), HEBO breaks at the following import: `from pymoo.algorithms.so_genetic_algorithm import GA`.

@alexanderimanicowenrivers @Alaya-in-Matrix

**Comment by Alaya-in-Matrix** [comment]
@Yard1 we've moved the repo of HEBO to https://github.com/huawei-noah/HEBO/tree/master/HEBO, and the pymoo dependency issue has been fixed.
