### ISSUE TITLE
Pretrained model for CURL

### ISSUE THREAD

**Issue by f0enix** [huawei-noah/noah-research#6]
Hi,
Can you provide the pretrained model for CURL. i would like to do some inference on it.
Thanks

**Comment by smcdonagh** [comment]
Hi,
Thanks for your interest. We have added an additional 'CURL for RGB images' code and corresponding pre-trained weights.

**Comment by f0enix** [comment]
i cannot find any pretrained weights in the CURL folder.

**Comment by smcdonagh** [comment]
Hi f0enix, 

we have had to remove the pretrained weights for now as this is pending our internal review. I will update this thread once we are able to upload them. Apologies for the delay!
