### ISSUE TITLE
[CLIFF] About the training code

### ISSUE THREAD

**Issue by puppet101** [huawei-noah/noah-research#96]
Hi, thanks for sharing this great work. Do you have any plan to release the training code?

**Comment by zhihaolee** [comment]
Sorry that we don't have this plan at present.
However, it is quite easy to implement the CLIFF training based on `SPIN`, using the CLIFF input and supervision shown in the demo code:
https://github.com/huawei-noah/noah-research/blob/7956f49b22dd7b5f1b18f660766342b9f68c9d92/CLIFF/demo.py#L124-L134

And even with the original SPIN training code, you can get quite better performance with the released CLIFF pseudo-GT of the COCO and MPII datasets [[Google Drive](
    https://drive.google.com/drive/folders/1EmSZwaDULhT9m1VvH7YOpCXwBWgYrgwP?usp=sharing)].

**Comment by puppet101** [comment]
OK, thank you!
