### ISSUE TITLE
[CLIFF] Is it able to inference in real time?

### ISSUE THREAD

**Issue by sylyt62** [huawei-noah/noah-research#97]
Congrats for your wonderful work! Can you share the inference speed of your experiments? It will be sooo great if it could be done in real time.

**Comment by zhihaolee** [comment]
It depends on what devices you use. 
The network design is very simple, so the inference latency should be close to the image classification task using the same backbone.
Here are the results of testing on Tesla P100:

|  Backbone   | #instance/s  |
| :----  | :----: |
| ResNet-50 | 26.46 |
| HRNet-W48 | 9.14 |

Besides the model inference, the latency shown in the table includes the image pre-processing and SMPL forwark kinematics.
You can test by yourself just using the setting of `--batch_size 1`.
